<?xml version="1.0"?>
<workspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workingsets.xsd">
  <projects>
  <project><name>shell_boot_frdmk66f</name><path>.</path><open>true</open><activeconfig>debug</activeconfig><buildreferences config="debug">false</buildreferences><activeconfig>release</activeconfig><buildreferences config="release">false</buildreferences></project></projects>
  <workingsets>
  <workingSet editPageId="org.eclipse.cdt.ui.CElementWorkingSetPage" id="1323268527287_1" label="shell_boot" name="shell_boot"><item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/shell_boot_frdmk66f" type="4"/></workingSet></workingsets>
  <cdtconfigurations>
  <workingSet name="shell_boot"><config name="debug"><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="shell_boot_frdmk66f" configName="debug"/></config><config name="release"><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="shell_boot_frdmk66f" configName="release"/></config></workingSet></cdtconfigurations>
</workspace>
