/********************************************************************/
/* Coldfire C Header File
 *
 *     Date      : 2010/07/19
 *     Revision  : 0.4
 *
 *     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
 *
 *     http      : www.freescale.com
 *     mail      : support@freescale.com
 */

#ifndef __MCF54418_PAD_H__
#define __MCF54418_PAD_H__


/*********************************************************************
*
* Common GPIO
*
*********************************************************************/

/* Register read/write macros */
#define MCF_PAD_PAR_FBCTL                    (*(vuint8 *)(0xEC094048))
#define MCF_PAD_PAR_BE                       (*(vuint8 *)(0xEC094049))
#define MCF_PAD_PAR_CS                       (*(vuint8 *)(0xEC09404A))
#define MCF_PAD_PAR_CANI2C                   (*(vuint8 *)(0xEC09404B))
#define MCF_PAD_PAR_IRQ0H                    (*(vuint8 *)(0xEC09404C))
#define MCF_PAD_PAR_IRQ0L                    (*(vuint8 *)(0xEC09404D))
#define MCF_PAD_PAR_DSPIOWH                  (*(vuint8 *)(0xEC09404E))
#define MCF_PAD_PAR_DSPIOWL                  (*(vuint8 *)(0xEC09404F))
#define MCF_PAD_PAR_TIMER                    (*(vuint8 *)(0xEC094050))
#define MCF_PAD_PAR_UART2                    (*(vuint8 *)(0xEC094051))
#define MCF_PAD_PAR_UART1                    (*(vuint8 *)(0xEC094052))
#define MCF_PAD_PAR_UART0                    (*(vuint8 *)(0xEC094053))
#define MCF_PAD_PAR_SDHCH                    (*(vuint8 *)(0xEC094054))
#define MCF_PAD_PAR_SDHCL                    (*(vuint8 *)(0xEC094055))
#define MCF_PAD_PAR_SIMP0H                   (*(vuint8 *)(0xEC094056))
#define MCF_PAD_PAR_SIMP0L                   (*(vuint8 *)(0xEC094057))
#define MCF_PAD_PAR_SSI0H                    (*(vuint8 *)(0xEC094058))
#define MCF_PAD_PAR_SSI0L                    (*(vuint8 *)(0xEC094059))
#define MCF_PAD_PAR_DEBUGH1                  (*(vuint8 *)(0xEC09405A))
#define MCF_PAD_PAR_DEBUGH0                  (*(vuint8 *)(0xEC09405B))
#define MCF_PAD_PAR_DEBUGL                   (*(vuint8 *)(0xEC09405C))
#define MCF_PAD_PAR_FEC                      (*(vuint8 *)(0xEC09405E))
#define MCF_PAD_MSCR_SDRAMC                  (*(vuint8 *)(0xEC094060))
#define MCF_PAD_SRCR_FB1                     (*(vuint8 *)(0xEC094064))
#define MCF_PAD_SRCR_FB2                     (*(vuint8 *)(0xEC094065))
#define MCF_PAD_SRCR_FB3                     (*(vuint8 *)(0xEC094066))
#define MCF_PAD_SRCR_FB4                     (*(vuint8 *)(0xEC094067))
#define MCF_PAD_SRCR_DSPIOW                  (*(vuint8 *)(0xEC094068))
#define MCF_PAD_SRCR_CANI2C                  (*(vuint8 *)(0xEC094069))
#define MCF_PAD_SRCR_IRQ0                    (*(vuint8 *)(0xEC09406A))
#define MCF_PAD_SRCR_TIMER                   (*(vuint8 *)(0xEC09406B))
#define MCF_PAD_SRCR_UART                    (*(vuint8 *)(0xEC09406C))
#define MCF_PAD_SRCR_FEC                     (*(vuint8 *)(0xEC09406D))
#define MCF_PAD_SRCR_SDHC                    (*(vuint8 *)(0xEC09406E))
#define MCF_PAD_SRCR_SIMP0                   (*(vuint8 *)(0xEC09406F))
#define MCF_PAD_SRCR_SSI0                    (*(vuint8 *)(0xEC094070))
#define MCF_PAD_URTS_POL                     (*(vuint16*)(0xEC094074))
#define MCF_PAD_UCTS_POL                     (*(vuint16*)(0xEC094076))
#define MCF_PAD_UTXD_WOM                     (*(vuint16*)(0xEC094078))
#define MCF_PAD_URXD_WOM                     (*(vuint32*)(0xEC09407C))
#define MCF_PAD_HCR1                         (*(vuint32*)(0xEC094080))
#define MCF_PAD_HCR0                         (*(vuint32*)(0xEC094084))


/* Bit definitions and macros for MCF_PAD_PAR_FBCTL */
#define MCF_PAD_PAR_FBCTL_PAR_TA(x)          (((x)&0x3)<<0)
#define MCF_PAD_PAR_FBCTL_PAR_TA_GPIO        (0)
#define MCF_PAD_PAR_FBCTL_PAR_TA_NFC         (0x1)
#define MCF_PAD_PAR_FBCTL_PAR_TA_FB          (0x3)
#define MCF_PAD_PAR_FBCTL_PAR_RW             (0x4)
#define MCF_PAD_PAR_FBCTL_PAR_FBCLK          (0x8)
#define MCF_PAD_PAR_FBCTL_PAR_FBCLK_GPIO     (0)
#define MCF_PAD_PAR_FBCTL_PAR_FBCLK_FBCLK    (0x8)
#define MCF_PAD_PAR_FBCTL_PAR_OE(x)          (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_FBCTL_PAR_OE_GPIO        (0)
#define MCF_PAD_PAR_FBCTL_PAR_OE_TBST        (0x20)
#define MCF_PAD_PAR_FBCTL_PAR_OE_RE          (0x30)
#define MCF_PAD_PAR_FBCTL_PAR_ALE(x)         (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_FBCTL_PAR_ALE_GPIO       (0)
#define MCF_PAD_PAR_FBCTL_PAR_ALE_TS         (0x80)
#define MCF_PAD_PAR_FBCTL_PAR_ALE_ALE        (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_BE */
#define MCF_PAD_PAR_BE_PAR_BE0(x)            (((x)&0x3)<<0)
#define MCF_PAD_PAR_BE_PAR_BE0_GPIO          (0)
#define MCF_PAD_PAR_BE_PAR_BE0_TSIZ0         (0x2)
#define MCF_PAD_PAR_BE_PAR_BE0_BE            (0x3)
#define MCF_PAD_PAR_BE_PAR_BE1(x)            (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_BE_PAR_BE1_GPIO          (0)
#define MCF_PAD_PAR_BE_PAR_BE1_TSIZ1         (0x8)
#define MCF_PAD_PAR_BE_PAR_BE1_BE            (0xC)
#define MCF_PAD_PAR_BE_PAR_BE2(x)            (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_BE_PAR_BE2_GPIO          (0)
#define MCF_PAD_PAR_BE_PAR_BE2_A0_CLE        (0x10)
#define MCF_PAD_PAR_BE_PAR_BE2_CS2           (0x20)
#define MCF_PAD_PAR_BE_PAR_BE2_BE            (0x30)
#define MCF_PAD_PAR_BE_PAR_BE3(x)            (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_BE_PAR_BE3_GPIO          (0)
#define MCF_PAD_PAR_BE_PAR_BE3_A1_ALE        (0x40)
#define MCF_PAD_PAR_BE_PAR_BE3_CS3           (0x80)
#define MCF_PAD_PAR_BE_PAR_BE3_BE            (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_CS */
#define MCF_PAD_PAR_CS_PAR_CS0               (0x1)
#define MCF_PAD_PAR_CS_PAR_CS0_GPIO          (0)
#define MCF_PAD_PAR_CS_PAR_CS0_CS            (0x1)
#define MCF_PAD_PAR_CS_PAR_CS1(x)            (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_CS_PAR_CS1_GPIO          (0)
#define MCF_PAD_PAR_CS_PAR_CS1_CE            (0x4)
#define MCF_PAD_PAR_CS_PAR_CS1_CS            (0xC)
#define MCF_PAD_PAR_CS_PAR_CS4(x)            (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_CS_PAR_CS4_GPIO          (0)
#define MCF_PAD_PAR_CS_PAR_CS4_DREQ1         (0x20)
#define MCF_PAD_PAR_CS_PAR_CS4_CS            (0x30)
#define MCF_PAD_PAR_CS_PAR_CS5(x)            (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_CS_PAR_CS5_GPIO          (0)
#define MCF_PAD_PAR_CS_PAR_CS5_DACK1         (0x80)
#define MCF_PAD_PAR_CS_PAR_CS5_CS            (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_CANI2C */
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_RX(x)    (((x)&0x3)<<0)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_RX_GPIO  (0)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_RX_SDA1  (0x1)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_RX_U9RXD (0x2)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_RX_RX1   (0x3)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_TX(x)    (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_TX_GPIO  (0)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_TX_SCL1  (0x4)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_TX_U9TXD (0x8)
#define MCF_PAD_PAR_CANI2C_PAR_CAN1_TX_TX1   (0xC)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SDA(x)   (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SDA_GPIO (0)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SDA_RX0  (0x10)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SDA_U8RXD (0x20)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SDA_SDA1 (0x30)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SCL(x)   (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SCL_GPIO (0)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SCL_TX0  (0x40)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SCL_U8TXD (0x80)
#define MCF_PAD_PAR_CANI2C_PAR_I2C0_SCL_SCL0 (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_IRQ0H */
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ01          (0x1)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ01_GPIO     (0)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ01_IRQ      (0x1)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ04(x)       (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ04_GPIO     (0)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ04_DREQ0    (0x8)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ04_IRQ      (0xC)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ07          (0x10)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ07_GPIO     (0)
#define MCF_PAD_PAR_IRQ0H_PAR_IRQ07_IRQ      (0x10)

/* Bit definitions and macros for MCF_PAD_PAR_IRQ0L */
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ02(x)       (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ02_GPIO     (0)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ02_VBUSOC   (0x4)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ02_PCS2     (0x8)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ02_IRQ      (0xC)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ03(x)       (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ03_GPIO     (0)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ03_VBUSEN   (0x10)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ03_PCS3     (0x20)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ03_IRQ      (0x30)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ06(x)       (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ06_GPIO     (0)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ06_USB_CLKIN (0x40)
#define MCF_PAD_PAR_IRQ0L_PAR_IRQ06_IRQ      (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_DSPIOWH */
#define MCF_PAD_PAR_DSPIOWH_PAR_PCS0(x)      (((x)&0x3)<<0)
#define MCF_PAD_PAR_DSPIOWH_PAR_PCS0_GPIO    (0)
#define MCF_PAD_PAR_DSPIOWH_PAR_PCS0_SDHC_DAT3 (0x1)
#define MCF_PAD_PAR_DSPIOWH_PAR_PCS0_SDA3    (0x2)
#define MCF_PAD_PAR_DSPIOWH_PAR_PCS0_DSPI0_PCS0 (0x3)
#define MCF_PAD_PAR_DSPIOWH_PAR_SCK(x)       (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_DSPIOWH_PAR_SCK_GPIO     (0)
#define MCF_PAD_PAR_DSPIOWH_PAR_SCK_SDHC_CLK (0x4)
#define MCF_PAD_PAR_DSPIOWH_PAR_SCK_SCL3     (0x8)
#define MCF_PAD_PAR_DSPIOWH_PAR_SCK_DSPI0_SBFCK (0xC)
#define MCF_PAD_PAR_DSPIOWH_PAR_SOUT(x)      (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_DSPIOWH_PAR_SOUT_GPIO    (0)
#define MCF_PAD_PAR_DSPIOWH_PAR_SOUT_SDHC_DAT0 (0x10)
#define MCF_PAD_PAR_DSPIOWH_PAR_SOUT_U3TXD   (0x20)
#define MCF_PAD_PAR_DSPIOWH_PAR_SOUT_DSPI0_SBFDO (0x30)
#define MCF_PAD_PAR_DSPIOWH_PAR_SIN(x)       (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_DSPIOWH_PAR_SIN_GPIO     (0)
#define MCF_PAD_PAR_DSPIOWH_PAR_SIN_SDHC_CMD (0x40)
#define MCF_PAD_PAR_DSPIOWH_PAR_SIN_U3RXD    (0x80)
#define MCF_PAD_PAR_DSPIOWH_PAR_SIN_DSPI0_SBFDI (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_DSPIOWL */
#define MCF_PAD_PAR_DSPIOWL_PAR_OWDAT(x)     (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_DSPIOWL_PAR_OWDAT_GPIO   (0)
#define MCF_PAD_PAR_DSPIOWL_PAR_OWDAT_DACK0  (0x20)
#define MCF_PAD_PAR_DSPIOWL_PAR_OWDAT_OWDAT  (0x30)
#define MCF_PAD_PAR_DSPIOWL_PAR_PCS1         (0x80)
#define MCF_PAD_PAR_DSPIOWL_PAR_PCS1_GPIO    (0)
#define MCF_PAD_PAR_DSPIOWL_PAR_PCS1_DSPI0_PCS1 (0x80)

/* Bit definitions and macros for MCF_PAD_PAR_TIMER */
#define MCF_PAD_PAR_TIMER_PAR_T0IN(x)        (((x)&0x3)<<0)
#define MCF_PAD_PAR_TIMER_PAR_T0IN_GPIO      (0)
#define MCF_PAD_PAR_TIMER_PAR_T0IN_VBUSOC    (0x1)
#define MCF_PAD_PAR_TIMER_PAR_T0IN_T0OUT     (0x2)
#define MCF_PAD_PAR_TIMER_PAR_T0IN_T0IN      (0x3)
#define MCF_PAD_PAR_TIMER_PAR_T1IN(x)        (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_TIMER_PAR_T1IN_GPIO      (0)
#define MCF_PAD_PAR_TIMER_PAR_T1IN_SDHC_DAT1 (0x4)
#define MCF_PAD_PAR_TIMER_PAR_T1IN_T1OUT     (0x8)
#define MCF_PAD_PAR_TIMER_PAR_T1IN_T1IN      (0xC)
#define MCF_PAD_PAR_TIMER_PAR_T2IN(x)        (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_TIMER_PAR_T2IN_GPIO      (0)
#define MCF_PAD_PAR_TIMER_PAR_T2IN_SDHC_DAT2 (0x10)
#define MCF_PAD_PAR_TIMER_PAR_T2IN_T2OUT     (0x20)
#define MCF_PAD_PAR_TIMER_PAR_T2IN_T2IN      (0x30)
#define MCF_PAD_PAR_TIMER_PAR_T3IN(x)        (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_TIMER_PAR_T3IN_GPIO      (0)
#define MCF_PAD_PAR_TIMER_PAR_T3IN_VBUSEN    (0x40)
#define MCF_PAD_PAR_TIMER_PAR_T3IN_T3OUT     (0x80)
#define MCF_PAD_PAR_TIMER_PAR_T3IN_T3IN      (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_UART2 */
#define MCF_PAD_PAR_UART2_PAR_TXD(x)         (((x)&0x3)<<0)
#define MCF_PAD_PAR_UART2_PAR_TXD_GPIO       (0)
#define MCF_PAD_PAR_UART2_PAR_TXD_SSI1_TXD   (0x1)
#define MCF_PAD_PAR_UART2_PAR_TXD_PWM_B3     (0x2)
#define MCF_PAD_PAR_UART2_PAR_TXD_U2TXD      (0x3)
#define MCF_PAD_PAR_UART2_PAR_RXD(x)         (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_UART2_PAR_RXD_GPIO       (0)
#define MCF_PAD_PAR_UART2_PAR_RXD_SSI1_RXD   (0x4)
#define MCF_PAD_PAR_UART2_PAR_RXD_PWM_A3     (0x8)
#define MCF_PAD_PAR_UART2_PAR_RXD_U2RXD      (0xC)
#define MCF_PAD_PAR_UART2_PAR_RTS(x)         (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_UART2_PAR_RTS_GPIO       (0)
#define MCF_PAD_PAR_UART2_PAR_RTS_SSI1_FS    (0x10)
#define MCF_PAD_PAR_UART2_PAR_RTS_U6RXD      (0x20)
#define MCF_PAD_PAR_UART2_PAR_RTS_U2RTS      (0x30)
#define MCF_PAD_PAR_UART2_PAR_CTS(x)         (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_UART2_PAR_CTS_GPIO       (0)
#define MCF_PAD_PAR_UART2_PAR_CTS_SSI1_BCLK  (0x40)
#define MCF_PAD_PAR_UART2_PAR_CTS_U6TXD      (0x80)
#define MCF_PAD_PAR_UART2_PAR_CTS_U2CTS      (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_UART1 */
#define MCF_PAD_PAR_UART1_PAR_TXD(x)         (((x)&0x3)<<0)
#define MCF_PAD_PAR_UART1_PAR_TXD_GPIO       (0)
#define MCF_PAD_PAR_UART1_PAR_TXD_DSPI3_SOUT (0x1)
#define MCF_PAD_PAR_UART1_PAR_TXD_SCL5       (0x2)
#define MCF_PAD_PAR_UART1_PAR_TXD_U1TXD      (0x3)
#define MCF_PAD_PAR_UART1_PAR_RXD(x)         (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_UART1_PAR_RXD_GPIO       (0)
#define MCF_PAD_PAR_UART1_PAR_RXD_DSPI3_SIN  (0x4)
#define MCF_PAD_PAR_UART1_PAR_RXD_SDA5       (0x8)
#define MCF_PAD_PAR_UART1_PAR_RXD_U1RXD      (0xC)
#define MCF_PAD_PAR_UART1_PAR_RTS(x)         (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_UART1_PAR_RTS_GPIO       (0)
#define MCF_PAD_PAR_UART1_PAR_RTS_DSPI3_PCS0 (0x10)
#define MCF_PAD_PAR_UART1_PAR_RTS_U5RXD      (0x20)
#define MCF_PAD_PAR_UART1_PAR_RTS_U1RTS      (0x30)
#define MCF_PAD_PAR_UART1_PAR_CTS(x)         (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_UART1_PAR_CTS_GPIO       (0)
#define MCF_PAD_PAR_UART1_PAR_CTS_DSPI3_SCK  (0x40)
#define MCF_PAD_PAR_UART1_PAR_CTS_U5TXD      (0x80)
#define MCF_PAD_PAR_UART1_PAR_CTS_U1CTS      (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_UART0 */
#define MCF_PAD_PAR_UART0_PAR_TXD(x)         (((x)&0x3)<<0)
#define MCF_PAD_PAR_UART0_PAR_TXD_GPIO       (0)
#define MCF_PAD_PAR_UART0_PAR_TXD_DSPI2_SOUT (0x1)
#define MCF_PAD_PAR_UART0_PAR_TXD_SCL4       (0x2)
#define MCF_PAD_PAR_UART0_PAR_TXD_U0TXD      (0x3)
#define MCF_PAD_PAR_UART0_PAR_RXD(x)         (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_UART0_PAR_RXD_GPIO       (0)
#define MCF_PAD_PAR_UART0_PAR_RXD_DSPI2_SIN  (0x4)
#define MCF_PAD_PAR_UART0_PAR_RXD_SDA4       (0x8)
#define MCF_PAD_PAR_UART0_PAR_RXD_U0RXD      (0xC)
#define MCF_PAD_PAR_UART0_PAR_RTS(x)         (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_UART0_PAR_RTS_GPIO       (0)
#define MCF_PAD_PAR_UART0_PAR_RTS_DSPI2_PSC0 (0x10)
#define MCF_PAD_PAR_UART0_PAR_RTS_U4RXD      (0x20)
#define MCF_PAD_PAR_UART0_PAR_RTS_U0RTS      (0x30)
#define MCF_PAD_PAR_UART0_PAR_CTS(x)         (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_UART0_PAR_CTS_GPIO       (0)
#define MCF_PAD_PAR_UART0_PAR_CTS_DSPI2_SCK  (0x40)
#define MCF_PAD_PAR_UART0_PAR_CTS_U4TXD      (0x80)
#define MCF_PAD_PAR_UART0_PAR_CTS_U0CTS      (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_SDHCH */
#define MCF_PAD_PAR_SDHCH_PAR_DATA0(x)       (((x)&0x3)<<0)
#define MCF_PAD_PAR_SDHCH_PAR_DATA0_GPIO     (0)
#define MCF_PAD_PAR_SDHCH_PAR_DATA0_DSPI1_SOUT (0x1)
#define MCF_PAD_PAR_SDHCH_PAR_DATA0_PWM_B2   (0x2)
#define MCF_PAD_PAR_SDHCH_PAR_DATA0_SDHC_DAT0 (0x3)
#define MCF_PAD_PAR_SDHCH_PAR_DATA1(x)       (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_SDHCH_PAR_DATA1_GPIO     (0)
#define MCF_PAD_PAR_SDHCH_PAR_DATA1_DSPI1_PCS1 (0x4)
#define MCF_PAD_PAR_SDHCH_PAR_DATA1_PWM_A2   (0x8)
#define MCF_PAD_PAR_SDHCH_PAR_DATA1_SDHC_DAT1 (0xC)
#define MCF_PAD_PAR_SDHCH_PAR_DATA2(x)       (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_SDHCH_PAR_DATA2_GPIO     (0)
#define MCF_PAD_PAR_SDHCH_PAR_DATA2_DSPI1_PCS2 (0x10)
#define MCF_PAD_PAR_SDHCH_PAR_DATA2_PWM_B1   (0x20)
#define MCF_PAD_PAR_SDHCH_PAR_DATA2_SDHC_DAT2 (0x30)
#define MCF_PAD_PAR_SDHCH_PAR_DATA3(x)       (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_SDHCH_PAR_DATA3_GPIO     (0)
#define MCF_PAD_PAR_SDHCH_PAR_DATA3_DSPI1_PCS0 (0x40)
#define MCF_PAD_PAR_SDHCH_PAR_DATA3_PWM_A1   (0x80)
#define MCF_PAD_PAR_SDHCH_PAR_DATA3_SDHC_DAT3 (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_SDHCL */
#define MCF_PAD_PAR_SDHCL_PAR_CLK(x)         (((x)&0x3)<<0)
#define MCF_PAD_PAR_SDHCL_PAR_CLK_GPIO       (0)
#define MCF_PAD_PAR_SDHCL_PAR_CLK_DSPI1_SCK  (0x1)
#define MCF_PAD_PAR_SDHCL_PAR_CLK_PWM_A0     (0x2)
#define MCF_PAD_PAR_SDHCL_PAR_CLK_SDHC_CLK   (0x3)
#define MCF_PAD_PAR_SDHCL_PAR_CMD(x)         (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_SDHCL_PAR_CMD_GPIO       (0)
#define MCF_PAD_PAR_SDHCL_PAR_CMD_DSPI1_SIN  (0x4)
#define MCF_PAD_PAR_SDHCL_PAR_CMD_PWM_B0     (0x8)
#define MCF_PAD_PAR_SDHCL_PAR_CMD_SDHC_CMD   (0xC)

/* Bit definitions and macros for MCF_PAD_PAR_SIMP0H */
#define MCF_PAD_PAR_SIMP0H_PAR_PD(x)         (((x)&0x3)<<0)
#define MCF_PAD_PAR_SIMP0H_PAR_PD_GPIO       (0)
#define MCF_PAD_PAR_SIMP0H_PAR_PD_SDHC_DAT5  (0x1)
#define MCF_PAD_PAR_SIMP0H_PAR_PD_PWM_SYNC   (0x2)
#define MCF_PAD_PAR_SIMP0H_PAR_PD_SIM0_PD    (0x3)
#define MCF_PAD_PAR_SIMP0H_PAR_RST(x)        (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_SIMP0H_PAR_RST_GPIO      (0)
#define MCF_PAD_PAR_SIMP0H_PAR_RST_SDHC_DAT6 (0x4)
#define MCF_PAD_PAR_SIMP0H_PAR_RST_PWM_FORCE (0x8)
#define MCF_PAD_PAR_SIMP0H_PAR_RST_SIM0_RST  (0xC)
#define MCF_PAD_PAR_SIMP0H_PAR_VEN(x)        (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_SIMP0H_PAR_VEN_GPIO      (0)
#define MCF_PAD_PAR_SIMP0H_PAR_VEN_PWM_FAULT0 (0x20)
#define MCF_PAD_PAR_SIMP0H_PAR_VEN_SIM0_VEN  (0x30)
#define MCF_PAD_PAR_SIMP0H_PAR_DATA(x)       (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_SIMP0H_PAR_DATA_GPIO     (0)
#define MCF_PAD_PAR_SIMP0H_PAR_DATA_SDHC_DAT7 (0x40)
#define MCF_PAD_PAR_SIMP0H_PAR_DATA_PWM_FAULT2 (0x80)
#define MCF_PAD_PAR_SIMP0H_PAR_DATA_SIM0_DATA (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_SIMP0L */
#define MCF_PAD_PAR_SIMP0L_PAR_CLK(x)        (((x)&0x3)<<0)
#define MCF_PAD_PAR_SIMP0L_PAR_CLK_GPIO      (0)
#define MCF_PAD_PAR_SIMP0L_PAR_CLK_SDHC_DAT4 (0x1)
#define MCF_PAD_PAR_SIMP0L_PAR_CLK_PWM_FAULT1 (0x2)
#define MCF_PAD_PAR_SIMP0L_PAR_CLK_SIM0_CLK  (0x3)

/* Bit definitions and macros for MCF_PAD_PAR_SSI0H */
#define MCF_PAD_PAR_SSI0H_PAR_MCLK(x)        (((x)&0x3)<<0)
#define MCF_PAD_PAR_SSI0H_PAR_MCLK_GPIO      (0)
#define MCF_PAD_PAR_SSI0H_PAR_MCLK_SIM1_CLK  (0x1)
#define MCF_PAD_PAR_SSI0H_PAR_MCLK_SSI_CLKIN (0x2)
#define MCF_PAD_PAR_SSI0H_PAR_MCLK_SSI0_MCLK (0x3)
#define MCF_PAD_PAR_SSI0H_PAR_FS(x)          (((x)&0x3)<<0x2)
#define MCF_PAD_PAR_SSI0H_PAR_FS_GPIO        (0)
#define MCF_PAD_PAR_SSI0H_PAR_FS_SIM1_RST    (0x4)
#define MCF_PAD_PAR_SSI0H_PAR_FS_U7TXD       (0x8)
#define MCF_PAD_PAR_SSI0H_PAR_FS_SSI0_FS     (0xC)
#define MCF_PAD_PAR_SSI0H_PAR_TXD(x)         (((x)&0x3)<<0x4)
#define MCF_PAD_PAR_SSI0H_PAR_TXD_GPIO       (0)
#define MCF_PAD_PAR_SSI0H_PAR_TXD_SIM1_DATA  (0x10)
#define MCF_PAD_PAR_SSI0H_PAR_TXD_SCL2       (0x20)
#define MCF_PAD_PAR_SSI0H_PAR_TXD_SSI0_TXD   (0x30)
#define MCF_PAD_PAR_SSI0H_PAR_RXD(x)         (((x)&0x3)<<0x6)
#define MCF_PAD_PAR_SSI0H_PAR_RXD_GPIO       (0)
#define MCF_PAD_PAR_SSI0H_PAR_RXD_SIM1_VEN   (0x40)
#define MCF_PAD_PAR_SSI0H_PAR_RXD_SDA2       (0x80)
#define MCF_PAD_PAR_SSI0H_PAR_RXD_SSI0_RXD   (0xC0)

/* Bit definitions and macros for MCF_PAD_PAR_SSI0L */
#define MCF_PAD_PAR_SSI0L_PAR_BCLK(x)        (((x)&0x3)<<0)
#define MCF_PAD_PAR_SSI0L_PAR_BCLK_GPIO      (0)
#define MCF_PAD_PAR_SSI0L_PAR_BCLK_SIM1_PD   (0x1)
#define MCF_PAD_PAR_SSI0L_PAR_BCLK_U7RXD     (0x2)
#define MCF_PAD_PAR_SSI0L_PAR_BCLK_SSI0_BCLK (0x3)

/* Bit definitions and macros for MCF_PAD_PAR_DEBUGH1 */
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA0       (0x1)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA0_GPIO  (0)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA0_DDATA0 (0x1)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA1       (0x4)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA1_GPIO  (0)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA1_DDATA1 (0x4)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA2       (0x10)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA2_GPIO  (0)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA2_DDATA2 (0x10)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA3       (0x40)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA3_GPIO  (0)
#define MCF_PAD_PAR_DEBUGH1_PAR_DDATA3_DDATA3 (0x40)

/* Bit definitions and macros for MCF_PAD_PAR_DEBUGH0 */
#define MCF_PAD_PAR_DEBUGH0_PAR_PST0         (0x1)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST0_GPIO    (0)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST0_PST0    (0x1)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST1         (0x4)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST1_GPIO    (0)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST1_PST1    (0x4)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST2         (0x10)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST2_GPIO    (0)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST2_PST2    (0x10)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST3         (0x40)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST3_GPIO    (0)
#define MCF_PAD_PAR_DEBUGH0_PAR_PST3_PST3    (0x40)

/* Bit definitions and macros for MCF_PAD_PAR_DEBUGL */
#define MCF_PAD_PAR_DEBUGL_PAR_ALLPST        (0x1)
#define MCF_PAD_PAR_DEBUGL_PAR_ALLPST_GPIO   (0)
#define MCF_PAD_PAR_DEBUGL_PAR_ALLPST_ALLPST (0x1)

/* Bit definitions and macros for MCF_PAD_PAR_FEC */
#define MCF_PAD_PAR_FEC_PAR_FEC(x)           (((x)&0xF)<<0)
#define MCF_PAD_PAR_FEC_PAR_FEC_MII_FULL     (0)
#define MCF_PAD_PAR_FEC_PAR_FEC_MII_NON_FULL (0x1)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_RMII1_FULL (0x3)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_RMII1_NON_FULL (0x4)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_FULL_RMII1_NON_FULL (0x5)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_NON_FULL_RMII1_FULL (0x6)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_FULL   (0x7)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_FULL_ULPI (0x8)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_NON_MII (0x9)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII0_NON_MII_ULPI (0xA)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII1_FULL   (0xB)
#define MCF_PAD_PAR_FEC_PAR_FEC_RMII1_NON_MII (0xC)
#define MCF_PAD_PAR_FEC_PAR_FEC_ALL_GPIO     (0xD)

/* Bit definitions and macros for MCF_PAD_MSCR_SDRAMC */
#define MCF_PAD_MSCR_SDRAMC_MSC(x)           (((x)&0x3)<<0)
#define MCF_PAD_MSCR_SDRAMC_MSC_HS_DDR2      (0)
#define MCF_PAD_MSCR_SDRAMC_MSC_FS_DDR2      (0x1)
#define MCF_PAD_MSCR_SDRAMC_MSC_DDR1         (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_FB1 */
#define MCF_PAD_SRCR_FB1_SRE_FB1(x)          (((x)&0x3)<<0)
#define MCF_PAD_SRCR_FB1_SRE_FB1_SR_LOWEST   (0)
#define MCF_PAD_SRCR_FB1_SRE_FB1_SR_LOW      (0x1)
#define MCF_PAD_SRCR_FB1_SRE_FB1_SR_HIGH     (0x2)
#define MCF_PAD_SRCR_FB1_SRE_FB1_SR_HIGHEST  (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_FB2 */
#define MCF_PAD_SRCR_FB2_SRE_FB2(x)          (((x)&0x3)<<0)
#define MCF_PAD_SRCR_FB2_SRE_FB2_SR_LOWEST   (0)
#define MCF_PAD_SRCR_FB2_SRE_FB2_SR_LOW      (0x1)
#define MCF_PAD_SRCR_FB2_SRE_FB2_SR_HIGH     (0x2)
#define MCF_PAD_SRCR_FB2_SRE_FB2_SR_HIGHEST  (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_FB3 */
#define MCF_PAD_SRCR_FB3_SRE_FB3(x)          (((x)&0x3)<<0)
#define MCF_PAD_SRCR_FB3_SRE_FB3_SR_LOWEST   (0)
#define MCF_PAD_SRCR_FB3_SRE_FB3_SR_LOW      (0x1)
#define MCF_PAD_SRCR_FB3_SRE_FB3_SR_HIGH     (0x2)
#define MCF_PAD_SRCR_FB3_SRE_FB3_SR_HIGHEST  (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_FB4 */
#define MCF_PAD_SRCR_FB4_SRE_FB4(x)          (((x)&0x3)<<0)
#define MCF_PAD_SRCR_FB4_SRE_FB4_SR_LOWEST   (0)
#define MCF_PAD_SRCR_FB4_SRE_FB4_SR_LOW      (0x1)
#define MCF_PAD_SRCR_FB4_SRE_FB4_SR_HIGH     (0x2)
#define MCF_PAD_SRCR_FB4_SRE_FB4_SR_HIGHEST  (0x3)
#define MCF_PAD_SRCR_FB4_SRE_FB5(x)          (((x)&0x3)<<0x2)
#define MCF_PAD_SRCR_FB4_SRE_FB5_SR_LOWEST   (0)
#define MCF_PAD_SRCR_FB4_SRE_FB5_SR_LOW      (0x4)
#define MCF_PAD_SRCR_FB4_SRE_FB5_SR_HIGH     (0x8)
#define MCF_PAD_SRCR_FB4_SRE_FB5_SR_HIGHEST  (0xC)

/* Bit definitions and macros for MCF_PAD_SRCR_DSPIOW */
#define MCF_PAD_SRCR_DSPIOW_SRE_DSPI0(x)     (((x)&0x3)<<0)
#define MCF_PAD_SRCR_DSPIOW_SRE_DSPI0_SR_LOWEST (0)
#define MCF_PAD_SRCR_DSPIOW_SRE_DSPI0_SR_LOW (0x1)
#define MCF_PAD_SRCR_DSPIOW_SRE_DSPI0_SR_HIGH (0x2)
#define MCF_PAD_SRCR_DSPIOW_SRE_DSPI0_SR_HIGHEST (0x3)
#define MCF_PAD_SRCR_DSPIOW_SRE_OWDAT(x)     (((x)&0x3)<<0x4)
#define MCF_PAD_SRCR_DSPIOW_SRE_OWDAT_SR_LOWEST (0)
#define MCF_PAD_SRCR_DSPIOW_SRE_OWDAT_SR_LOW (0x10)
#define MCF_PAD_SRCR_DSPIOW_SRE_OWDAT_SR_HIGH (0x20)
#define MCF_PAD_SRCR_DSPIOW_SRE_OWDAT_SR_HIGHEST (0x30)

/* Bit definitions and macros for MCF_PAD_SRCR_CANI2C */
#define MCF_PAD_SRCR_CANI2C_SRE_I2C0(x)      (((x)&0x3)<<0)
#define MCF_PAD_SRCR_CANI2C_SRE_I2C0_SR_LOWEST (0)
#define MCF_PAD_SRCR_CANI2C_SRE_I2C0_SR_LOW  (0x1)
#define MCF_PAD_SRCR_CANI2C_SRE_I2C0_SR_HIGH (0x2)
#define MCF_PAD_SRCR_CANI2C_SRE_I2C0_SR_HIGHEST (0x3)
#define MCF_PAD_SRCR_CANI2C_SRE_CAN1(x)      (((x)&0x3)<<0x2)
#define MCF_PAD_SRCR_CANI2C_SRE_CAN1_SR_LOWEST (0)
#define MCF_PAD_SRCR_CANI2C_SRE_CAN1_SR_LOW  (0x4)
#define MCF_PAD_SRCR_CANI2C_SRE_CAN1_SR_HIGH (0x8)
#define MCF_PAD_SRCR_CANI2C_SRE_CAN1_SR_HIGHEST (0xC)

/* Bit definitions and macros for MCF_PAD_SRCR_IRQ0 */
#define MCF_PAD_SRCR_IRQ0_SRE_IRQ0(x)        (((x)&0x3)<<0)
#define MCF_PAD_SRCR_IRQ0_SRE_IRQ0_SR_LOWEST (0)
#define MCF_PAD_SRCR_IRQ0_SRE_IRQ0_SR_LOW    (0x1)
#define MCF_PAD_SRCR_IRQ0_SRE_IRQ0_SR_HIGH   (0x2)
#define MCF_PAD_SRCR_IRQ0_SRE_IRQ0_SR_HIGHEST (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_TIMER */
#define MCF_PAD_SRCR_TIMER_SRE_TIMER0(x)     (((x)&0x3)<<0)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER0_SR_LOWEST (0)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER0_SR_LOW (0x1)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER0_SR_HIGH (0x2)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER0_SR_HIGHEST (0x3)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER1(x)     (((x)&0x3)<<0x2)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER1_SR_LOWEST (0)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER1_SR_LOW (0x4)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER1_SR_HIGH (0x8)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER1_SR_HIGHEST (0xC)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER2(x)     (((x)&0x3)<<0x4)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER2_SR_LOWEST (0)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER2_SR_LOW (0x10)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER2_SR_HIGH (0x20)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER2_SR_HIGHEST (0x30)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER3(x)     (((x)&0x3)<<0x6)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER3_SR_LOWEST (0)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER3_SR_LOW (0x40)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER3_SR_HIGH (0x80)
#define MCF_PAD_SRCR_TIMER_SRE_TIMER3_SR_HIGHEST (0xC0)

/* Bit definitions and macros for MCF_PAD_SRCR_UART */
#define MCF_PAD_SRCR_UART_SRE_UART0(x)       (((x)&0x3)<<0)
#define MCF_PAD_SRCR_UART_SRE_UART0_SR_LOWEST (0)
#define MCF_PAD_SRCR_UART_SRE_UART0_SR_LOW   (0x1)
#define MCF_PAD_SRCR_UART_SRE_UART0_SR_HIGH  (0x2)
#define MCF_PAD_SRCR_UART_SRE_UART0_SR_HIGHEST (0x3)
#define MCF_PAD_SRCR_UART_SRE_UART1(x)       (((x)&0x3)<<0x2)
#define MCF_PAD_SRCR_UART_SRE_UART1_SR_LOWEST (0)
#define MCF_PAD_SRCR_UART_SRE_UART1_SR_LOW   (0x4)
#define MCF_PAD_SRCR_UART_SRE_UART1_SR_HIGH  (0x8)
#define MCF_PAD_SRCR_UART_SRE_UART1_SR_HIGHEST (0xC)
#define MCF_PAD_SRCR_UART_SRE_UART2(x)       (((x)&0x3)<<0x4)
#define MCF_PAD_SRCR_UART_SRE_UART2_SR_LOWEST (0)
#define MCF_PAD_SRCR_UART_SRE_UART2_SR_LOW   (0x10)
#define MCF_PAD_SRCR_UART_SRE_UART2_SR_HIGH  (0x20)
#define MCF_PAD_SRCR_UART_SRE_UART2_SR_HIGHEST (0x30)

/* Bit definitions and macros for MCF_PAD_SRCR_FEC */
#define MCF_PAD_SRCR_FEC_SRE_RMII1(x)        (((x)&0x3)<<0)
#define MCF_PAD_SRCR_FEC_SRE_RMII1_SR_LOWEST (0)
#define MCF_PAD_SRCR_FEC_SRE_RMII1_SR_LOW    (0x1)
#define MCF_PAD_SRCR_FEC_SRE_RMII1_SR_HIGH   (0x2)
#define MCF_PAD_SRCR_FEC_SRE_RMII1_SR_HIGHEST (0x3)
#define MCF_PAD_SRCR_FEC_SRE_RMII0(x)        (((x)&0x3)<<0x2)
#define MCF_PAD_SRCR_FEC_SRE_RMII0_SR_LOWEST (0)
#define MCF_PAD_SRCR_FEC_SRE_RMII0_SR_LOW    (0x4)
#define MCF_PAD_SRCR_FEC_SRE_RMII0_SR_HIGH   (0x8)
#define MCF_PAD_SRCR_FEC_SRE_RMII0_SR_HIGHEST (0xC)

/* Bit definitions and macros for MCF_PAD_SRCR_SDHC */
#define MCF_PAD_SRCR_SDHC_SRE_SDHC(x)        (((x)&0x3)<<0)
#define MCF_PAD_SRCR_SDHC_SRE_SDHC_SR_LOWEST (0)
#define MCF_PAD_SRCR_SDHC_SRE_SDHC_SR_LOW    (0x1)
#define MCF_PAD_SRCR_SDHC_SRE_SDHC_SR_HIGH   (0x2)
#define MCF_PAD_SRCR_SDHC_SRE_SDHC_SR_HIGHEST (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_SIMP0 */
#define MCF_PAD_SRCR_SIMP0_SRE_SIMP0(x)      (((x)&0x3)<<0)
#define MCF_PAD_SRCR_SIMP0_SRE_SIMP0_SR_LOWEST (0)
#define MCF_PAD_SRCR_SIMP0_SRE_SIMP0_SR_LOW  (0x1)
#define MCF_PAD_SRCR_SIMP0_SRE_SIMP0_SR_HIGH (0x2)
#define MCF_PAD_SRCR_SIMP0_SRE_SIMP0_SR_HIGHEST (0x3)

/* Bit definitions and macros for MCF_PAD_SRCR_SSI0 */
#define MCF_PAD_SRCR_SSI0_SRE_SSI0(x)        (((x)&0x3)<<0)
#define MCF_PAD_SRCR_SSI0_SRE_SSI0_SR_LOWEST (0)
#define MCF_PAD_SRCR_SSI0_SRE_SSI0_SR_LOW    (0x1)
#define MCF_PAD_SRCR_SSI0_SRE_SSI0_SR_HIGH   (0x2)
#define MCF_PAD_SRCR_SSI0_SRE_SSI0_SR_HIGHEST (0x3)

/* Bit definitions and macros for MCF_PAD_URTS_POL */
#define MCF_PAD_URTS_POL_U0INV               (0x1)
#define MCF_PAD_URTS_POL_U0INV_DIS           (0)
#define MCF_PAD_URTS_POL_U0INV_EN            (0x1)
#define MCF_PAD_URTS_POL_U1INV               (0x2)
#define MCF_PAD_URTS_POL_U1INV_DIS           (0)
#define MCF_PAD_URTS_POL_U1INV_EN            (0x2)
#define MCF_PAD_URTS_POL_U2INV               (0x4)
#define MCF_PAD_URTS_POL_U2INV_DIS           (0)
#define MCF_PAD_URTS_POL_U2INV_EN            (0x4)

/* Bit definitions and macros for MCF_PAD_UCTS_POL */
#define MCF_PAD_UCTS_POL_U0INV               (0x1)
#define MCF_PAD_UCTS_POL_U0INV_DIS           (0)
#define MCF_PAD_UCTS_POL_U0INV_EN            (0x1)
#define MCF_PAD_UCTS_POL_U1INV               (0x2)
#define MCF_PAD_UCTS_POL_U1INV_DIS           (0)
#define MCF_PAD_UCTS_POL_U1INV_EN            (0x2)
#define MCF_PAD_UCTS_POL_U2INV               (0x4)
#define MCF_PAD_UCTS_POL_U2INV_DIS           (0)
#define MCF_PAD_UCTS_POL_U2INV_EN            (0x4)

/* Bit definitions and macros for MCF_PAD_UTXD_WOM */
#define MCF_PAD_UTXD_WOM_U0WOM               (0x1)
#define MCF_PAD_UTXD_WOM_U0WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U0WOM_EN            (0x1)
#define MCF_PAD_UTXD_WOM_U1WOM               (0x2)
#define MCF_PAD_UTXD_WOM_U1WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U1WOM_EN            (0x2)
#define MCF_PAD_UTXD_WOM_U2WOM               (0x4)
#define MCF_PAD_UTXD_WOM_U2WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U2WOM_EN            (0x4)
#define MCF_PAD_UTXD_WOM_U3WOM               (0x8)
#define MCF_PAD_UTXD_WOM_U3WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U3WOM_EN            (0x8)
#define MCF_PAD_UTXD_WOM_U4WOM               (0x10)
#define MCF_PAD_UTXD_WOM_U4WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U4WOM_EN            (0x10)
#define MCF_PAD_UTXD_WOM_U5WOM               (0x20)
#define MCF_PAD_UTXD_WOM_U5WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U5WOM_EN            (0x20)
#define MCF_PAD_UTXD_WOM_U6WOM               (0x40)
#define MCF_PAD_UTXD_WOM_U6WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U6WOM_EN            (0x40)
#define MCF_PAD_UTXD_WOM_U7WOM               (0x80)
#define MCF_PAD_UTXD_WOM_U7WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U7WOM_EN            (0x80)
#define MCF_PAD_UTXD_WOM_U8WOM               (0x100)
#define MCF_PAD_UTXD_WOM_U8WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U8WOM_EN            (0x100)
#define MCF_PAD_UTXD_WOM_U9WOM               (0x200)
#define MCF_PAD_UTXD_WOM_U9WOM_DIS           (0)
#define MCF_PAD_UTXD_WOM_U9WOM_EN            (0x200)

/* Bit definitions and macros for MCF_PAD_URXD_WOM */
#define MCF_PAD_URXD_WOM_U0WOM(x)            (((x)&0x3)<<0)
#define MCF_PAD_URXD_WOM_U0WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U0WOM_CONNECT       (0x1)
#define MCF_PAD_URXD_WOM_U0WOM_AUTOMATIC     (0x2)
#define MCF_PAD_URXD_WOM_U1WOM(x)            (((x)&0x3)<<0x2)
#define MCF_PAD_URXD_WOM_U1WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U1WOM_CONNECT       (0x4)
#define MCF_PAD_URXD_WOM_U1WOM_AUTOMATIC     (0x8)
#define MCF_PAD_URXD_WOM_U2WOM(x)            (((x)&0x3)<<0x4)
#define MCF_PAD_URXD_WOM_U2WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U2WOM_CONNECT       (0x10)
#define MCF_PAD_URXD_WOM_U2WOM_AUTOMATIC     (0x20)
#define MCF_PAD_URXD_WOM_U3WOM(x)            (((x)&0x3)<<0x6)
#define MCF_PAD_URXD_WOM_U3WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U3WOM_CONNECT       (0x40)
#define MCF_PAD_URXD_WOM_U3WOM_AUTOMATIC     (0x80)
#define MCF_PAD_URXD_WOM_U4WOM(x)            (((x)&0x3)<<0x8)
#define MCF_PAD_URXD_WOM_U4WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U4WOM_CONNECT       (0x100)
#define MCF_PAD_URXD_WOM_U4WOM_AUTOMATIC     (0x200)
#define MCF_PAD_URXD_WOM_U5WOM(x)            (((x)&0x3)<<0xA)
#define MCF_PAD_URXD_WOM_U5WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U5WOM_CONNECT       (0x400)
#define MCF_PAD_URXD_WOM_U5WOM_AUTOMATIC     (0x800)
#define MCF_PAD_URXD_WOM_U6WOM(x)            (((x)&0x3)<<0xC)
#define MCF_PAD_URXD_WOM_U6WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U6WOM_CONNECT       (0x1000)
#define MCF_PAD_URXD_WOM_U6WOM_AUTOMATIC     (0x2000)
#define MCF_PAD_URXD_WOM_U7WOM(x)            (((x)&0x3)<<0xE)
#define MCF_PAD_URXD_WOM_U7WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U7WOM_CONNECT       (0x4000)
#define MCF_PAD_URXD_WOM_U7WOM_AUTOMATIC     (0x8000)
#define MCF_PAD_URXD_WOM_U8WOM(x)            (((x)&0x3)<<0x10)
#define MCF_PAD_URXD_WOM_U8WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U8WOM_CONNECT       (0x10000)
#define MCF_PAD_URXD_WOM_U8WOM_AUTOMATIC     (0x20000)
#define MCF_PAD_URXD_WOM_U9WOM(x)            (((x)&0x3)<<0x12)
#define MCF_PAD_URXD_WOM_U9WOM_DISCONNECT    (0)
#define MCF_PAD_URXD_WOM_U9WOM_CONNECT       (0x40000)
#define MCF_PAD_URXD_WOM_U9WOM_AUTOMATIC     (0x80000)

/* Bit definitions and macros for MCF_PAD_HCR1 */
#define MCF_PAD_HCR1_PB0                     (0x1)
#define MCF_PAD_HCR1_PB0_DIS                 (0)
#define MCF_PAD_HCR1_PB0_EN                  (0x1)
#define MCF_PAD_HCR1_PB1                     (0x2)
#define MCF_PAD_HCR1_PB1_DIS                 (0)
#define MCF_PAD_HCR1_PB1_EN                  (0x2)
#define MCF_PAD_HCR1_PB2                     (0x4)
#define MCF_PAD_HCR1_PB2_DIS                 (0)
#define MCF_PAD_HCR1_PB2_EN                  (0x4)
#define MCF_PAD_HCR1_PC1                     (0x8)
#define MCF_PAD_HCR1_PC1_DIS                 (0)
#define MCF_PAD_HCR1_PC1_EN                  (0x8)
#define MCF_PAD_HCR1_PC2                     (0x10)
#define MCF_PAD_HCR1_PC2_DIS                 (0)
#define MCF_PAD_HCR1_PC2_EN                  (0x10)
#define MCF_PAD_HCR1_PC3                     (0x20)
#define MCF_PAD_HCR1_PC3_DIS                 (0)
#define MCF_PAD_HCR1_PC3_EN                  (0x20)
#define MCF_PAD_HCR1_PC4                     (0x40)
#define MCF_PAD_HCR1_PC4_DIS                 (0)
#define MCF_PAD_HCR1_PC4_EN                  (0x40)
#define MCF_PAD_HCR1_PC5                     (0x80)
#define MCF_PAD_HCR1_PC5_DIS                 (0)
#define MCF_PAD_HCR1_PC5_EN                  (0x80)
#define MCF_PAD_HCR1_PC6                     (0x100)
#define MCF_PAD_HCR1_PC6_DIS                 (0)
#define MCF_PAD_HCR1_PC6_EN                  (0x100)
#define MCF_PAD_HCR1_PC7                     (0x200)
#define MCF_PAD_HCR1_PC7_DIS                 (0)
#define MCF_PAD_HCR1_PC7_EN                  (0x200)
#define MCF_PAD_HCR1_PD3                     (0x400)
#define MCF_PAD_HCR1_PD3_DIS                 (0)
#define MCF_PAD_HCR1_PD3_EN                  (0x400)
#define MCF_PAD_HCR1_PD4                     (0x800)
#define MCF_PAD_HCR1_PD4_DIS                 (0)
#define MCF_PAD_HCR1_PD4_EN                  (0x800)
#define MCF_PAD_HCR1_PD5                     (0x1000)
#define MCF_PAD_HCR1_PD5_DIS                 (0)
#define MCF_PAD_HCR1_PD5_EN                  (0x1000)
#define MCF_PAD_HCR1_PD6                     (0x2000)
#define MCF_PAD_HCR1_PD6_DIS                 (0)
#define MCF_PAD_HCR1_PD6_EN                  (0x2000)
#define MCF_PAD_HCR1_PD7                     (0x4000)
#define MCF_PAD_HCR1_PD7_DIS                 (0)
#define MCF_PAD_HCR1_PD7_EN                  (0x4000)
#define MCF_PAD_HCR1_PE0                     (0x8000)
#define MCF_PAD_HCR1_PE0_DIS                 (0)
#define MCF_PAD_HCR1_PE0_EN                  (0x8000)
#define MCF_PAD_HCR1_PE1                     (0x10000)
#define MCF_PAD_HCR1_PE1_DIS                 (0)
#define MCF_PAD_HCR1_PE1_EN                  (0x10000)
#define MCF_PAD_HCR1_PE2                     (0x20000)
#define MCF_PAD_HCR1_PE2_DIS                 (0)
#define MCF_PAD_HCR1_PE2_EN                  (0x20000)
#define MCF_PAD_HCR1_PE3                     (0x40000)
#define MCF_PAD_HCR1_PE3_DIS                 (0)
#define MCF_PAD_HCR1_PE3_EN                  (0x40000)
#define MCF_PAD_HCR1_PE4                     (0x80000)
#define MCF_PAD_HCR1_PE4_DIS                 (0)
#define MCF_PAD_HCR1_PE4_EN                  (0x80000)
#define MCF_PAD_HCR1_PE5                     (0x100000)
#define MCF_PAD_HCR1_PE5_DIS                 (0)
#define MCF_PAD_HCR1_PE5_EN                  (0x100000)
#define MCF_PAD_HCR1_PE6                     (0x200000)
#define MCF_PAD_HCR1_PE6_DIS                 (0)
#define MCF_PAD_HCR1_PE6_EN                  (0x200000)
#define MCF_PAD_HCR1_PF3                     (0x400000)
#define MCF_PAD_HCR1_PF3_DIS                 (0)
#define MCF_PAD_HCR1_PF3_EN                  (0x400000)
#define MCF_PAD_HCR1_PF4                     (0x800000)
#define MCF_PAD_HCR1_PF4_DIS                 (0)
#define MCF_PAD_HCR1_PF4_EN                  (0x800000)
#define MCF_PAD_HCR1_PF5                     (0x1000000)
#define MCF_PAD_HCR1_PF5_DIS                 (0)
#define MCF_PAD_HCR1_PF5_EN                  (0x1000000)
#define MCF_PAD_HCR1_PF6                     (0x2000000)
#define MCF_PAD_HCR1_PF6_DIS                 (0)
#define MCF_PAD_HCR1_PF6_EN                  (0x2000000)
#define MCF_PAD_HCR1_PF7                     (0x4000000)
#define MCF_PAD_HCR1_PF7_DIS                 (0)
#define MCF_PAD_HCR1_PF7_EN                  (0x4000000)
#define MCF_PAD_HCR1_PG0                     (0x8000000)
#define MCF_PAD_HCR1_PG0_DIS                 (0)
#define MCF_PAD_HCR1_PG0_EN                  (0x8000000)
#define MCF_PAD_HCR1_PG1                     (0x10000000)
#define MCF_PAD_HCR1_PG1_DIS                 (0)
#define MCF_PAD_HCR1_PG1_EN                  (0x10000000)
#define MCF_PAD_HCR1_PG2                     (0x20000000)
#define MCF_PAD_HCR1_PG2_DIS                 (0)
#define MCF_PAD_HCR1_PG2_EN                  (0x20000000)
#define MCF_PAD_HCR1_PG3                     (0x40000000)
#define MCF_PAD_HCR1_PG3_DIS                 (0)
#define MCF_PAD_HCR1_PG3_EN                  (0x40000000)
#define MCF_PAD_HCR1_PG4                     (0x80000000)
#define MCF_PAD_HCR1_PG4_DIS                 (0)
#define MCF_PAD_HCR1_PG4_EN                  (0x80000000)

/* Bit definitions and macros for MCF_PAD_HCR0 */
#define MCF_PAD_HCR0_PH3                     (0x1)
#define MCF_PAD_HCR0_PH3_DIS                 (0)
#define MCF_PAD_HCR0_PH3_EN                  (0x1)
#define MCF_PAD_HCR0_PH4                     (0x2)
#define MCF_PAD_HCR0_PH4_DIS                 (0)
#define MCF_PAD_HCR0_PH4_EN                  (0x2)
#define MCF_PAD_HCR0_PH5                     (0x4)
#define MCF_PAD_HCR0_PH5_DIS                 (0)
#define MCF_PAD_HCR0_PH5_EN                  (0x4)
#define MCF_PAD_HCR0_PH6                     (0x8)
#define MCF_PAD_HCR0_PH6_DIS                 (0)
#define MCF_PAD_HCR0_PH6_EN                  (0x8)
#define MCF_PAD_HCR0_PH7                     (0x10)
#define MCF_PAD_HCR0_PH7_DIS                 (0)
#define MCF_PAD_HCR0_PH7_EN                  (0x10)
#define MCF_PAD_HCR0_PE7                     (0x20)
#define MCF_PAD_HCR0_PE7_DIS                 (0)
#define MCF_PAD_HCR0_PE7_EN                  (0x20)
#define MCF_PAD_HCR0_PD0                     (0x40)
#define MCF_PAD_HCR0_PD0_DIS                 (0)
#define MCF_PAD_HCR0_PD0_EN                  (0x40)
#define MCF_PAD_HCR0_PD1                     (0x80)
#define MCF_PAD_HCR0_PD1_DIS                 (0)
#define MCF_PAD_HCR0_PD1_EN                  (0x80)
#define MCF_PAD_HCR0_PD2                     (0x100)
#define MCF_PAD_HCR0_PD2_DIS                 (0)
#define MCF_PAD_HCR0_PD2_EN                  (0x100)
#define MCF_PAD_HCR0_PK0                     (0x200)
#define MCF_PAD_HCR0_PK0_DIS                 (0)
#define MCF_PAD_HCR0_PK0_EN                  (0x200)
#define MCF_PAD_HCR0_PK3                     (0x400)
#define MCF_PAD_HCR0_PK3_DIS                 (0)
#define MCF_PAD_HCR0_PK3_EN                  (0x400)


#endif /* __MCF54418_PAD_H__ */
